import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AuthContextProvider } from "@/context/userContext";
import QueryProvider from "@/components/queryProvider/queryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#45bbda] ${inter.className}`}>
        <QueryProvider>
          <AuthContextProvider>
            <div className="max-w-[100vw] md:max-w-[1366px] min-h-screen md:mx-auto md:my-0 py-0 px-2 md:px-[60px] flex flex-col justify-between  ">
              <Navbar />
              {children}
            </div>
          </AuthContextProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
